### ISSUE TITLE
Futaba MA switch support

### ISSUE THREAD

**Issue by AlexD97** [ai03-2725/yet-another-keyboard-builder#3]
Is it possible to add support for Futaba MA switches? Or maybe support the opportunity to give a custom size?

**Comment by ai03-2725** [comment]
Please feel free to submit a pull request with a generator for the switch type added - the process should be fairly self-explanatory given the amount of documentation.  
The one major thing I'll ask is that the cutout is either as provided by an official datasheet or proven in practice with real-world samples.

**Comment by ai03-2725** [comment]
Sorry for the long delay - merged #4 which solves this issue.
