### ISSUE TITLE
Support for plate-mounted stabilizers

### ISSUE THREAD

**Issue by takishim** [ai03-2725/yet-another-keyboard-builder#5]
Could you support plate-mounted stabilizers?

**Comment by sooyongjie** [comment]
I am pretty sure the "Cherry MX Spec" is for plate-mounted stabilizers.

**Comment by ai03-2725** [comment]
Sorry for the delay - yes, the MX spec is the standard for plate mount stabilizers.
As for other stabilizer types such as Costar-style, feel free to submit a PR - personally I haven't seen the need to add them in yet.
